name: extract_genes_gff
description: Extract genes (including tRNAs) from a GFF annotation and FASTA.
keywords: [gff, annotation, genes]
tools:
  - name: python
    homepage: https://www.python.org/
    licence: PSF-2.0
input:
  - meta: { type: map, description: Sample metadata }
  - fasta: { type: file, description: Assembled mitochondrial genome FASTA }
  - gff: { type: file, description: GFF annotation file }
output:
  - genes_dir: { type: directory, description: Extracted genes directory, pattern: "genes" }
authors: ["Tyler Peirce"]
maintainers: ["Tyler Peirce"]

