repository_type: pipeline

nf_core_version: 3.3.2

lint: {}

template:
  org: nf-core
  name: oceangenomesmitogenomes
  description: An nf-core pipeline for mitogenome assembly and LCA for species validation
  author: Tyler Peirce
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
