name: format_files
description: Standardise annotation files for GenBank submission and create CMT file.
keywords: [genbank, formatting, qc]
tools:
  - name: python
    homepage: https://www.python.org/
    licence: PSF-2.0
input:
  - meta: { type: map, description: Sample metadata }
  - species_name: { type: string, description: Nominal species name }
  - proceed_qc: { type: string, description: QC proceed flag (true/false) }
  - input_files: { type: directory, description: Emma output directory staged as input }
output:
  - processed_files: { type: files, description: processed FASTA/TBL/CMT, pattern: "processed/*.{fa,fasta,tbl,cmt}" }
  - gff: { type: files, description: processed FASTA and GFF, pattern: "processed/*.{fa,fasta},processed/*.gff" }
  - gb: { type: files, description: processed FASTA and TBL/GB, pattern: "processed/*.{fa,fasta,gb,tbl}" }
  - meta: { type: map, description: Passthrough metadata }
authors: ["Tyler Peirce"]
maintainers: ["Tyler Peirce"]

