name: extract_genes_gb
description: Extract coding sequences (CDS) and optionally genes from TBL/GB annotation and FASTA.
keywords: [genbank, tbl, gb, cds]
tools:
  - name: python
    homepage: https://www.python.org/
    licence: PSF-2.0
input:
  - meta: { type: map, description: Sample metadata }
  - fasta: { type: file, description: Assembled mitochondrial genome FASTA }
  - tbl: { type: file, description: TBL annotation file }
output:
  - cds_dir: { type: directory, description: Extracted CDS directory, pattern: "cds" }
  - cds_fastas: { type: files, description: Individual CDS FASTA files, pattern: "cds/*.fa" }
  - genes_dir: { type: directory, description: Optional genes directory, pattern: "genes" }
  - genes_fastas: { type: files, description: Optional gene FASTA files, pattern: "genes/*.fa" }
authors: ["Tyler Peirce"]
maintainers: ["Tyler Peirce"]

