name: create_samplesheet
description: Generate a samplesheet CSV from a directory of FASTQ files, inferring sample IDs and sequencing types.
keywords: [samplesheet, fastq]
tools:
  - name: python
    homepage: https://www.python.org/
    licence: PSF-2.0
input:
  - input_files: { type: files, description: List of input FASTQ files (globbed) }
  - output_name: { type: string, description: Output samplesheet filename }
output:
  - samplesheet: { type: file, description: Output samplesheet CSV }
authors: ["Tyler Peirce"]
maintainers: ["Tyler Peirce"]

