name: translate_genes
description: Translate coding sequences to protein sequences using a specified translation table.
keywords: [translation, proteins, cds]
tools:
  - name: python
    homepage: https://www.python.org/
    licence: PSF-2.0
input:
  - meta: { type: map, description: Sample metadata }
  - genes_dir: { type: directory, description: Directory containing extracted genes }
output:
  - proteins_dir: { type: directory, description: Translated protein FASTA files, pattern: "proteins" }
authors: ["Tyler Peirce"]
maintainers: ["Tyler Peirce"]

